@token = 1ab99ebf-8cc3-4072-85af-1d4d5d62932e

### Search Teams

GET http://localhost:8080/api/teams?name=Benfica





### Search Leagues

GET http://localhost:8080/api/leagues?team=211





### Create Group

POST http://localhost:8080/api/groups
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name" : "Awesome Group",
    "description": "This is the best group ever!"
}

###

POST http://localhost:8080/api/groups
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name" : "Awesome Group 2",
    "description": "This is the second best group ever!",
    "teams": [
        {
            "id": 211,
            "leagueId": 94,
            "season": 2022
        }
    ]
}





### Edit Group

PUT http://localhost:8080/api/groups/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name" : "Updated Awesome Group",
    "description": "The best group is even better!"
}

###

PUT http://localhost:8080/api/groups/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name" : "Awesome Group Again"
}





### List Group

GET http://localhost:8080/api/groups
Authorization: Bearer {{token}}





### Delete Group

DELETE http://localhost:8080/api/groups/1
Authorization: Bearer {{token}}





### Get Group Details

GET http://localhost:8080/api/groups/1
Authorization: Bearer {{token}}





### Add Teams to Group

POST http://localhost:8080/api/groups/1/teams
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "teams": [
        {
            "id": 211,
            "leagueId": 3,
            "season": 2019
        }
    ]
}





### Remove Team from Group

DELETE http://localhost:8080/api/groups/1/teams/211/leagues/3/seasons/2019
Authorization: Bearer {{token}}





### Create User

POST http://localhost:8080/api/users
Content-Type: application/json

{
    "name" : "Alice"
}