@url = http://localhost:8080
@token = 57d3cbc5-38a7-4730-8d27-9bf156f537c7

### Search Teams

GET {{url}}/api/teams?name=Benfica





### Search Leagues

GET {{url}}/api/leagues?team=211





### Create Group

POST {{url}}/api/groups
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name" : "Awesome Group",
    "description": "This is the best group ever!"
}

###

POST {{url}}/api/groups
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name" : "Awesome Group 2",
    "description": "This is the second best group ever!",
    "teams": [
        {
            "id": 211,
            "leagueId": 94,
            "season": 2022
        }
    ]
}





### Edit Group

PUT {{url}}/api/groups/D8S50ZMBAi_oj4EgQ4Kx
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name" : "Updated Awesome Group",
    "description": "The best group is even better!"
}

###

PUT {{url}}/api/groups/D8S50ZMBAi_oj4EgQ4Kx
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name" : "Awesome Group Again"
}





### List Group

GET {{url}}/api/groups
Authorization: Bearer {{token}}





### Delete Group

DELETE {{url}}/api/groups/D8S50ZMBAi_oj4EgQ4Kx
Authorization: Bearer {{token}}





### Get Group Details

GET {{url}}/api/groups/D8S50ZMBAi_oj4EgQ4Kx
Authorization: Bearer {{token}}





### Add Teams to Group

POST {{url}}/api/groups/D8S50ZMBAi_oj4EgQ4Kx/teams
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "teams": [
        {
            "id": 211,
            "leagueId": 3,
            "season": 2019
        }
    ]
}





### Remove Team from Group

DELETE {{url}}/api/groups/D8S50ZMBAi_oj4EgQ4Kx/teams/211/leagues/3/seasons/2019
Authorization: Bearer {{token}}





### Create User

POST {{url}}/api/users
Content-Type: application/json

{
    "name" : "Alice"
}